sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ultimatesoul/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true ultimatesoul/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreactsoul-env"
  bucket_name: "elasticbeanstalk-eu-north-1-253356440032"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY