sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ultimatesoul/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true ultimatesoul/docker-react npm run test -- --coverage